[package]
name = "aresrpg"
version = "0.1.0"
published-at = "0x5debcb263059ff464bff8cb3d6801de13f695fc88a5b0e87c374c8436b5edc3c"
edition = "2024.beta"

authors = ["Sceat (fetch@sceat.xyz)"]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.suifrens]
git = "https://github.com/MystenLabs/apps.git"
subdir = "suifrens/suifrens"
rev = "testnet"

[dependencies.vaporeon-nft]
git = "https://github.com/Sceat/vaporeon-nft.git"
rev = "testnet"

[dependencies.Kiosk]
git = "https://github.com/MystenLabs/apps.git"
subdir = "kiosk"
rev = "testnet"

[addresses]
aresrpg = "0x0"