[package]
name = "aresrpg"
version = "0.1.0"
published-at = "0x07b6008fed4c620b0404161a3eeb803bd94367cca4b0b18385bcae37305ff8e7"
edition = "2024.beta"

authors = ["Sceat (fetch@sceat.xyz)"]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[addresses]
aresrpg = "0x0"