[package]
name = "aresrpg"
version = "0.1.0"
published-at = "0xc0cd58effa83d08faad62a34048bfb0f2843d5dceb2663d8547a2a2b836596d6"
edition = "2024.beta"

authors = ["Sceat (fetch@sceat.xyz)"]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.Kiosk]
git = "https://github.com/MystenLabs/apps.git"
subdir = "kiosk"
rev = "testnet"

[addresses]
aresrpg = "0x0"