[package]
name = "aresrpg"
version = "0.1.0"
published-at = "0x3d55318f9b33eab092e2b7ca660030f252e18a20f151d9125e427a0ade7b99cc"
edition = "2024.beta"

authors = ["Sceat (fetch@sceat.xyz)"]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[addresses]
aresrpg = "0x0"