[package]
name = "aresrpg"
version = "0.1.0"
published-at = "0x68e06aee7966648c7b3258f02d5c7da2cf9b035727d6e9167c90e662f20e0406"
edition = "2024.beta"

authors = ["Sceat (fetch@sceat.xyz)"]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"
override = true

[dependencies.suifrens]
git = "https://github.com/MystenLabs/apps.git"
subdir = "suifrens/suifrens"
rev = "testnet"

[dependencies.vaporeon-nft]
git = "https://github.com/Sceat/vaporeon-nft.git"
rev = "testnet"

[dependencies.Kiosk]
git = "https://github.com/MystenLabs/apps.git"
subdir = "kiosk"
rev = "testnet"

[addresses]
aresrpg = "0x0"